# Generated by Django 5.0.3 on 2024-03-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.IntegerField(db_column='SNo', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='SName', max_length=100)),
                ('gender', models.CharField(db_column='Gender', max_length=100)),
                ('sclass', models.CharField(db_column='Sclass', max_length=100)),
                ('birthday', models.DateField(db_column='Birthday')),
                ('address', models.CharField(db_column='Address', max_length=100)),
                ('mobile', models.CharField(db_column='Mobile', max_length=100)),
                ('image', models.CharField(db_column='Image', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Student',
                'managed': True,
            },
        ),
    ]
